// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsmn4tSupcVpy29WRZp5DqRYIagS2C65k',
    appId: '1:1054134218630:web:e3ffaa6b453199ae474607',
    messagingSenderId: '1054134218630',
    projectId: 'fodinha-project-de0dd',
    authDomain: 'fodinha-project-de0dd.firebaseapp.com',
    databaseURL: 'https://fodinha-project-de0dd-default-rtdb.firebaseio.com',
    storageBucket: 'fodinha-project-de0dd.firebasestorage.app',
    measurementId: 'G-HJ0JH51FB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveecWA_p43XutFhCn-moezXKI89x5wsw',
    appId: '1:1054134218630:android:a5c0c7378395b1cb474607',
    messagingSenderId: '1054134218630',
    projectId: 'fodinha-project-de0dd',
    databaseURL: 'https://fodinha-project-de0dd-default-rtdb.firebaseio.com',
    storageBucket: 'fodinha-project-de0dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhsYnKDRXjz0tjqNZftf511kLt27MrR4Y',
    appId: '1:1054134218630:ios:43af500bd5947684474607',
    messagingSenderId: '1054134218630',
    projectId: 'fodinha-project-de0dd',
    databaseURL: 'https://fodinha-project-de0dd-default-rtdb.firebaseio.com',
    storageBucket: 'fodinha-project-de0dd.firebasestorage.app',
    iosBundleId: 'com.example.trucoRl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhsYnKDRXjz0tjqNZftf511kLt27MrR4Y',
    appId: '1:1054134218630:ios:43af500bd5947684474607',
    messagingSenderId: '1054134218630',
    projectId: 'fodinha-project-de0dd',
    databaseURL: 'https://fodinha-project-de0dd-default-rtdb.firebaseio.com',
    storageBucket: 'fodinha-project-de0dd.firebasestorage.app',
    iosBundleId: 'com.example.trucoRl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsmn4tSupcVpy29WRZp5DqRYIagS2C65k',
    appId: '1:1054134218630:web:7aed75e11f0acba5474607',
    messagingSenderId: '1054134218630',
    projectId: 'fodinha-project-de0dd',
    authDomain: 'fodinha-project-de0dd.firebaseapp.com',
    databaseURL: 'https://fodinha-project-de0dd-default-rtdb.firebaseio.com',
    storageBucket: 'fodinha-project-de0dd.firebasestorage.app',
    measurementId: 'G-MKGRSTMT11',
  );
}
